version: 0.0
os: linux
files:
  - source: ./bin/Release/net8.0/linux-x64/
    destination: /home/ubuntu/srv-02
file_exists_behavior: OVERWRITE
  

hooks:
  BeforeInstall: # place a dumb before install script to make things work (do not ask why)
    - location: ./scripts/before_install.sh
      timeout: 30
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 30
  ApplicationStart:
    - location: ./scripts/start.sh
      timeout: 30
  ApplicationStop:
    - location: ./scripts/stop.sh
      timeout: 30
